// Generated by `npm run build:vercel` — do not edit. Commit after build or let Vercel build generate it.
module.exports = (_req, res) => {
  res.status(503).json({
    error: 'API bundle not built. Run: npm run build:vercel',
  });
};
